# Generated by tools/gowin_tcl.py - do not edit, regenerate.
# Run from the tang/ directory:  gw_sh build.tcl

set_device -name GW2AR-18C GW2AR-LV18QN88C8/I7

add_file -type verilog "src/top.v"
add_file -type verilog "src/sys_pll.v"
add_file -type verilog "src/i2s_tx.v"
add_file -type verilog "src/zs256/tv80_core.v"
add_file -type verilog "src/zs256/tv80_alu.v"
add_file -type verilog "src/zs256/tv80_mcode.v"
add_file -type verilog "src/zs256/tv80_reg.v"
add_file -type verilog "src/zs256/z80bus.v"
add_file -type verilog "src/zs256/memmap.v"
add_file -type verilog "src/zs256/membus.v"
add_file -type verilog "src/zs256/sdram.v"
add_file -type verilog "src/zs256/screen.v"
add_file -type verilog "src/zs256/video.v"
add_file -type verilog "src/zs256/keyboard.v"
add_file -type verilog "src/zs256/ports.v"
add_file -type verilog "src/zs256/fdc.v"
add_file -type verilog "src/zs256/wd1793.sv"
add_file -type verilog "src/zs256/ay.v"
add_file -type verilog "src/zs256/ym2149.sv"
add_file -type verilog "src/zs256/gs.v"
add_file -type verilog "src/zs256/smuc.v"
add_file -type verilog "src/zs256/ide.v"
add_file -type verilog "src/zs256/rtc.v"
add_file -type verilog "src/zs256/nvram.v"
add_file -type verilog "src/zs256/sd_arbiter.v"
add_file -type verilog "src/zs256/poke.v"
add_file -type verilog "src/hdmi/hdmi_packet.v"
add_file -type verilog "src/hdmi/hdmi_serdes.v"
add_file -type verilog "src/hdmi/hdmi_tx.v"
add_file -type verilog "src/hdmi/tmds_channel.v"
add_file -type verilog "src/mister/flashwr.v"
add_file -type verilog "src/mister/coreload.v"
add_file -type verilog "src/mister/hid.v"
add_file -type verilog "src/mister/mcu_spi.v"
add_file -type verilog "src/mister/osd_u8g2.v"
add_file -type verilog "src/mister/sd_card.v"
add_file -type verilog "src/mister/sd_rw.v"
add_file -type verilog "src/mister/sdcmd_ctrl.v"
add_file -type verilog "src/mister/sector_dpram.v"
add_file -type verilog "src/mister/sysctrl.v"
add_file -type cst "src/zs256.cst"
add_file -type sdc "src/zs256.sdc"

set_option -top_module top
set_option -verilog_std sysv2017
set_option -global_freq 100.000
set_option -rw_check_on_ram 0
set_option -use_sspi_as_gpio 1
set_option -use_mspi_as_gpio 1
set_option -correct_hold_violation 1
set_option -output_base_name zs256

run all
